### ISSUE TITLE
Mac OS X Support

### ISSUE THREAD

**Issue by ngmgithub** [Hou5e/FoldingBrowser#6]
+1 vote for a Mac OS X binary.

**Comment by Hou5e** [comment]
I know...   you're not the first person to mention it. I've had it on the To Do List for a long time.

Having a Linux and Mac version is something I would like to do at some point. I know the current code base will not work for doing it though. I would need to start over with a new code base, and I won't have the required time needed for it in the near-term.

I'm going to close this ticket since it duplicates the item already on my To Do List that I work from.

Thanks for the input though!

If you would like to have a more interactive conversation about this, please find me in Discord:
CureCoin Discord Invite: https://discord.gg/jtztkFZ
FoldingCoin Discord Invite: https://discord.gg/CvZ7gAs
