### ISSUE TITLE
Malware found in v15

### ISSUE THREAD

**Issue by axmachina** [Hou5e/FoldingBrowser#7]
Hi, 

Was trying to get folding browser set up to play around but Norton scan flagged it as WS.Reputation.1.

Is this something I should worry about? 

Thanks!

**Comment by Hou5e** [comment]
That seems to happen sometimes because I'm not a large corporation like Microsoft. There is nothing wrong with the FoldingBrowser from my GitHub account. You can see the details of why Norton is flagging the file, and how to allow it: https://community.norton.com/en/forums/clarification-wsreputation1-detection

I'll have to submit a false positive report and wait a few days.
Thanks for the report though!

**Comment by axmachina** [comment]
Great, I'd figured as much just wanted to run by you.

Thanks!
